name = "memorial-site-worker"
main = "worker.js"
compatibility_date = "2023-01-01"

# KV命名空间绑定
# KV命名空间已创建，ID已更新
kv_namespaces = [
  { binding = "MEMORIAL_KV", id = "653ffd69ab4749b982e8bae166109a55" }
]

# 配置路由（可选）
# 如果你想使用自定义域名，可以在这里配置
# routes = [
#   { pattern = "api.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# 触发器配置
triggers = { crons = [] }

# 环境变量（可选）
# [vars]
# MY_VARIABLE = "my-value"